/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/counter/get": {
    post: operations["counter#get"];
  };
  "/counter/inc": {
    post: operations["counter#inc"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    int: number;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  "counter#get": {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["int"];
        };
      };
      default: {
        content: never;
      };
    };
  };
  "counter#inc": {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["int"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["int"];
        };
      };
      default: {
        content: never;
      };
    };
  };
}
